[package]
name = "chatty-types"
version = "0.0.1"
edition = "2021"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
